### ISSUE TITLE
celery setup with app factory pattern

### ISSUE THREAD

**Issue by mkfz** [level09/enferno#19]
I am having difficulties getting celery to work properly. Simple tasks run fine but when i want to use SQLAlchemy within a celery Task the application context is missing. I suspect this is due to a wrong setup of celery with the app factory pattern. Would be great if you could post a snippet of how you usually setup celery with enferno (since you mention this is one of the "built in features"). 
Thanks a lot!

**Comment by level09** [comment]
Hi @mkfz , 

This actually has already been done for you, the sample task that runs within the app context is inside the enferno/tasks/__init__.py file 

The "task" function should have access to your SQL Alchemy models and ORM. 

You can run celery by invoking the following command: 

`celery -A enferno.tasks worker `

Let me know if this works for you.

**Comment by mkfz** [comment]
Sorry for the late reply. That worked, tanks a lot. Somehow i had an empty init in my project therefore the issues. Since celery is somehow detached from the other extensions ATM, did you try to incorporate celery creation & setup into the app factory?  
Many thanks
Moritz

**Comment by level09** [comment]
Hi @mkfz , 
Glad to hear. 
I think that is possible but I don't think that is necessary, I think it is better to keep Celery decoupled from the Flask application as not all apps would require a background task queue, as well as it is meant to run as a separate process (I think that's why the old celery extension was discontinued).
